export interface Swatch {
  /** Stable identity used to match two cards. */
  readonly key: string;
  /** One CSS color (solid fill) or two (diagonal split fill). */
  readonly colors: readonly string[];
  /** Accessible label describing the swatch. */
  readonly name: string;
}

interface BaseColor {
  readonly id: string;
  readonly value: string;
  readonly name: string;
}

// A curated set of vivid, mutually-distinct colors. They are intentionally
// ordered so that neighbouring entries contrast strongly — this keeps the
// two-tone combinations (built from adjacent-ish entries) easy to tell apart.
const BASE_COLORS: readonly BaseColor[] = [
  { id: "red", value: "hsl(0 85% 55%)", name: "Red" },
  { id: "cyan", value: "hsl(188 88% 50%)", name: "Cyan" },
  { id: "yellow", value: "hsl(52 95% 55%)", name: "Yellow" },
  { id: "purple", value: "hsl(270 72% 62%)", name: "Purple" },
  { id: "green", value: "hsl(140 65% 42%)", name: "Green" },
  { id: "pink", value: "hsl(330 85% 65%)", name: "Pink" },
  { id: "blue", value: "hsl(222 82% 58%)", name: "Blue" },
  { id: "orange", value: "hsl(30 95% 52%)", name: "Orange" },
  { id: "lime", value: "hsl(85 75% 48%)", name: "Lime" },
  { id: "gray", value: "hsl(0 0% 60%)", name: "Gray" },
  { id: "brown", value: "hsl(22 55% 38%)", name: "Brown" },
  { id: "white", value: "hsl(0 0% 92%)", name: "White" },
];

/** Maximum number of distinct swatches we can produce. */
export const MAX_SWATCHES =
  BASE_COLORS.length + (BASE_COLORS.length * (BASE_COLORS.length - 1)) / 2;

function solid(base: BaseColor): Swatch {
  return { key: base.id, colors: [base.value], name: base.name };
}

function combo(a: BaseColor, b: BaseColor): Swatch {
  return {
    key: `${a.id}+${b.id}`,
    colors: [a.value, b.value],
    name: `${a.name} & ${b.name}`,
  };
}

/**
 * Generate `count` visually distinct swatches. Solid colors are used first;
 * once they run out we extend the palette with two-tone (diagonally split)
 * cards built from pairs of base colors. Pairs are generated by increasing
 * "distance" between base colors so the combinations stay spread out and
 * high-contrast rather than clustering on one color.
 */
export function generateSwatches(count: number): readonly Swatch[] {
  if (count <= 0) return [];

  const swatches: Swatch[] = BASE_COLORS.map(solid);

  const n = BASE_COLORS.length;
  for (let offset = 1; offset < n && swatches.length < count; offset++) {
    for (let i = 0; i + offset < n && swatches.length < count; i++) {
      swatches.push(combo(BASE_COLORS[i], BASE_COLORS[i + offset]));
    }
  }

  return swatches.slice(0, count);
}
