export interface Swatch {
  /** Stable identity used to match two cards. */
  readonly key: string;
  /** One CSS color (solid fill) or two (diagonal split fill). */
  readonly colors: readonly string[];
  /** Accessible label describing the swatch. */
  readonly name: string;
}

interface BaseColor {
  readonly id: string;
  readonly value: string;
  readonly name: string;
}

// A curated set of vivid, mutually-distinct colors. The set was chosen by a
// farthest-point search in OKLab space, constrained to stay bright enough to
// read on the dark board: every pair sits at least ~0.18 ΔE apart, the
// practical ceiling for eight clearly-different colors. Eight solids also give
// 8 + C(8,2) = 36 distinct swatches once two-tone cards are added — enough for
// the largest 32-pair board. Entries are interleaved (warm/cool, light/dark)
// so the two-tone combinations built from neighbours stay high-contrast.
const BASE_COLORS: readonly BaseColor[] = [
  { id: "red", value: "hsl(0 88% 52%)", name: "Red" },
  { id: "sky", value: "hsl(210 80% 68%)", name: "Sky" },
  { id: "yellow", value: "hsl(60 88% 52%)", name: "Yellow" },
  { id: "magenta", value: "hsl(300 88% 52%)", name: "Magenta" },
  { id: "green", value: "hsl(125 78% 50%)", name: "Green" },
  { id: "orange", value: "hsl(30 90% 58%)", name: "Orange" },
  { id: "blue", value: "hsl(240 88% 60%)", name: "Blue" },
  { id: "teal", value: "hsl(170 78% 68%)", name: "Teal" },
];

/** Maximum number of distinct swatches we can produce. */
export const MAX_SWATCHES =
  BASE_COLORS.length + (BASE_COLORS.length * (BASE_COLORS.length - 1)) / 2;

function solid(base: BaseColor): Swatch {
  return { key: base.id, colors: [base.value], name: base.name };
}

function combo(a: BaseColor, b: BaseColor): Swatch {
  return {
    key: `${a.id}+${b.id}`,
    colors: [a.value, b.value],
    name: `${a.name} & ${b.name}`,
  };
}

/**
 * Generate `count` visually distinct swatches. Solid colors are used first;
 * once they run out we extend the palette with two-tone (diagonally split)
 * cards built from pairs of base colors. Pairs are generated by increasing
 * "distance" between base colors so the combinations stay spread out and
 * high-contrast rather than clustering on one color.
 */
export function generateSwatches(count: number): readonly Swatch[] {
  if (count <= 0) return [];

  const swatches: Swatch[] = BASE_COLORS.map(solid);

  const n = BASE_COLORS.length;
  for (let offset = 1; offset < n && swatches.length < count; offset++) {
    for (let i = 0; i + offset < n && swatches.length < count; i++) {
      swatches.push(combo(BASE_COLORS[i], BASE_COLORS[i + offset]));
    }
  }

  return swatches.slice(0, count);
}
